config/routes.rb
Rails.application.routes.draw do
  get 'btc/index'
  get 'btc/new'
  post 'btc/create'
  get 'btc/show'
  post 'manager/index'
  get 'manager/index'
  post 'manager/login'
  get 'manager/login'
  get 'janken/janken'
  get 'home/index'
  get 'home/result'
  get 'main/index'
  get 'main/point'
  get 'main/sen'
  post 'top/login'
  root 'top#main'
  get 'top/main'
  get 'top/login'
  get 'top/logout'
  get 'users/index'
  get 'users/new'
  get 'users/show'
  get 'users/edit'
  post 'users/update'
  get 'users/update'
  resources :users, only: [:create, :index, :new, :edit, :show, :index, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/btc.rb
class Btc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :btc
  attr_accessor :password, :password_confirmation

def password=(val)
  if val.present?
    self.pass = BCrypt::Password.create(val)
  end
  @password = val
end

def self.authenticate(uid, pass)
  user = User.find_by_uid(uid)
  if user && BCrypt::Password.new(user.pass) == pass
    user
  else
    nil
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
   if session[:login_uid]
     User.find_by(uid: session[:login_uid])
   end
  end
  helper_method :current_user
end

app/controllers/btc_controller.rb
class BtcController < ApplicationController
  def index
    @btc = Btc.all
    redirect_to btc_new_path
  end

  def new
    @btc = Btc.new
  end

  def create
    @btc = Btc.new(
      uid: current_user,
      address: params[:btc][:address],
      amount: 0.001,
      request: 送金準備中)
    if @btc.save
      redirect_to main_index_path
    else
      render 'new'
    end
  end

  def show
    @btc = Btc.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def result
    @user = User.find_by(uid: session[:login_uid])
    jankens = ["グー", "チョキ","パー"]
    program_hand = rand(3)
    player_hand = params[:player_hand].to_i
    @a = "あなたの手:#{jankens[player_hand]}, 相手の手:#{jankens[program_hand]}"
      if player_hand == program_hand
        var = true
      elsif(player_hand == 0 && program_hand == 1)||(player_hand == 1 && program_hand == 2)||(player_hand == 2 && program_hand == 0)
        @result = "あなたの勝ちです"
        @user.exe += 50
        @user.save
        var = false
      else
        @result = "あなたの負けです"
        var = false
      end

      if var == true
        flash.now[:aiko] = "あいこです。もう一回選択してください"
        render("/home/index")
      else
        render("/home/result")
      end
  end
end

app/controllers/janken_controller.rb
class JankenController < ApplicationController
  def janken
   puts "[0]グー\n[1]チョキ\n[2]パー"

   player_hand = gets.to_i
   program_hand = rand(3)

   jankens = ["グー", "チョキ","パー"]
   puts "あなたの手:#{jankens[player_hand]}, 相手の手:#{jankens[program_hand]}"

   if player_hand == program_hand
     puts "あいこで"
     return true
   elsif(player_hand == 0 && program_hand == 1)||(player_hand == 1 && program_hand == 2)||(player_hand == 2 && program_hand == 0)
     puts "あなたの勝ちです"
     return false

   else
     puts "あなたの負けです"
     return false
   end
  end
  next_game = true

  while next_game
   next_game = janken
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @user = current_user
    @userall = User.all
    @u = @userall.sort_by(&:exe).reverse
  end

  def point
    @user = current_user
  end

  def sen
    @user = current_user
    if @user.exe >= 100
      @user.exe -= 100
      @user.save
      flash.now[:not] = "送金しました"
    else
      flash.now[:not] = "ポイント不足のため送金できませんでした"
    end
  end
end

app/controllers/manager_controller.rb
class ManagerController < ApplicationController
  def index

  end

  def login
    if ("abcde" == params[:uid] && "aaa" == params[:pass])
      render manager_index_path
    elsif params[:uid] == nil && params[:pass] == nil
    else
      flash.now[:error] = "ログインに失敗しました"
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
		if session[:login_uid]
      $id = User.find_by(uid: session[:login_uid]).id
			redirect_to main_index_path
		else
			redirect_to top_login_path
		end
	end

	def login
		user = User.authenticate(params[:uid], params[:pass])
		if user
			session[:login_uid] = params[:uid]
			redirect_to top_main_path
    elsif params[:uid] == nil && params[:pass] == nil
		else
      flash.now[:er] = "ログインに失敗しました"
			render top_login_path
		end
	end

	def logout
		session.delete(:login_uid)
		redirect_to top_login_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @users = User.new
  end

  def create
    @users = User.new(
      uid: params[:user][:uid],
      password: params[:user][:password],
      password_confirmation: params[:user][:password_confirmation],
      exe: 0)
    if @users.save
      redirect_to top_login_path
    else
      render 'new'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(
       uid: params[:user][:uid],
       password: params[:user][:password],
       password_confirmation: params[:user][:password_confirmation],
       exe: @user.exe)
    session[:login_uid] = params[:user][:uid]
    render users_show_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/btc_helper.rb
module BtcHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/janken_helper.rb
module JankenHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/btc/show.html.erb
<h1>Btc#show</h1>
<p>Find me in app/views/btc/show.html.erb</p>

app/views/home/index.html.erb
じゃんけん<br><hr>

<%= flash.now[:aiko] %><br>
<%= link_to "グー", home_result_path(player_hand: 0) %>
<%= link_to "チョキ", home_result_path(player_hand: 1) %>
<%= link_to "パー", home_result_path(player_hand: 2) %>

app/views/home/result.html.erb
<%= @a %><br>
<%= @result %>
<%= @user.exe %>

<%= link_to "戻る", main_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Work</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<%= Date.today %><br>
ようこそ<%= @user.uid %>さん<br>
現在のポイント：<%= @user.exe %>P

<br>
<%= link_to "じゃんけんをする", home_index_path %>
<br>
<%= link_to 'プロフィール表示', users_show_path %>
<%= link_to 'ログアウト', top_logout_path %>

<br><br>
ランキング<br>
<table border="1">
 <tr>
   <th>順位</th>
   <th>uid</th>
   <th>ポイント</th>
 </tr>
 <% rank = 0 %>
<% @u.each do |t| %>
 <tr>
   <% rank += 1 %>
   <td><%= rank %></td>
   <td><%= t.uid %></td>
   <td><%= t.exe %></td>
 </tr>
<% end %>
</table>

app/views/main/point.html.erb
現在のポイント：<%= @user.exe %>P


<table border="1">
	<tr>
		<th>ポイント</th>
		<th>BTC</th>
		<th>BTCアドレス</th>
		<th>送金</th>
	</tr>

	<tr>
		<td>100P</td>
		<td>0.001BTC</td>
		<td>address</td>
		<td>
			<%= link_to '送金依頼', main_sen_path %>
		</td>
	</tr>
</table>

<%= link_to 'プロフィールの表示', users_show_path %>
<%= link_to 'ホームに戻る', main_index_path %>

app/views/main/sen.html.erb
<%= flash.now[:not] %><br>
<% @user = User.find($id) %>
現在のポイント：<%= @user.exe %>P<br>
<%= link_to 'プロフィールの表示', users_show_path %>
<%= link_to 'ホームに戻る', main_index_path %>

app/views/manager/index.html.erb
<h1>Manager#index</h1>
<p>Find me in app/views/manager/index.html.erb</p>

app/views/manager/login.html.erb
<%= flash.now[:error] %>
<%= form_tag url: manager_index_path do %>
<table>
	<tr>
		<td><%= label_tag :uid, 'ID' %></td>
		<td><%= text_field_tag :uid %></td>
	</tr>
	<tr>
		<td><%= label_tag :pass, 'パスワード' %></td>
		<td><%= password_field_tag :pass %></td>
	</tr>
	<tr>
		<td colspan="2"><%= submit_tag 'ログイン' %></td>
	</tr>
</table>
<% end %>

<p>
	<%= link_to '戻る', top_login_path %>
</p>

app/views/top/login.html.erb
<%= flash.now[:er] %>
<%= form_tag url: top_login_path do %>
<table>
	<tr>
		<td><%= label_tag :uid, 'ID' %></td>
		<td><%= text_field_tag :uid %></td>
	</tr>
	<tr>
		<td><%= label_tag :pass, 'パスワード' %></td>
		<td><%= password_field_tag :pass %></td>
	</tr>
	<tr>
		<td colspan="2"><%= submit_tag 'ログイン' %></td>
	</tr>
</table>
<% end %>

<p>
	<%= link_to 'ユーザ登録', users_new_path %>
</p>
<p>
	<%= link_to 'ユーザ一覧', users_index_path %>
</p>
<p>
	<%= link_to '管理者ログイン', manager_login_path %>
</p>

app/views/users/edit.html.erb
<%= form_for @user, url: users_update_path  do |f| %>

<table>
	<tr>
		<td><%= f.label :uid, 'ID' %></td>
		<td><%= f.text_field :uid %></td>
	</tr>
	<tr>
		<td><%= f.label :password, 'パスワード' %></td>
		<td><%= f.password_field :password %></td>
	</tr>
	<tr>
		<td><%= f.label :password_confirmation, 'パスワード（確認）' %></td>
		<td><%= f.password_field :password_confirmation %></td>
	</tr>
	<tr>
		<td colspan="2"><%= f.submit '登録' %></td>
	</tr>
</table>

<% end %>

<%= link_to "戻る", users_show_path %>

app/views/users/index.html.erb
<table border="1">

	<tr>
		<th>user_id</th>
		<th>ID</th>
		<th>パスワード</th>
		<th>操作</th>
	</tr>

<% @users.each do |e| %>
	<tr>
		<td><%= e.id %></td>
		<td><%= e.uid %></td>
		<td><%= e.pass %></td>
		<td>
			<%= link_to '削除', user_path(e), method: :delete, data: { confirm: '削除していいですか？' } %>
		</td>
	</tr>

<% end %>

</table>

<p>
	<%= link_to 'ユーザ登録', new_user_path %>
</p>
<p>
	<%= link_to 'トップへ', top_login_path %>
</p>

app/views/users/new.html.erb
<%= form_for @users do |f| %>

<table>
	<tr>
		<td><%= f.label :uid, 'ID' %></td>
		<td><%= f.text_field :uid %></td>
	</tr>
	<tr>
		<td><%= f.label :password, 'パスワード' %></td>
		<td><%= f.password_field :password %></td>
	</tr>
	<tr>
		<td><%= f.label :password_confirmation, 'パスワード（確認）' %></td>
		<td><%= f.password_field :password_confirmation %></td>
	</tr>
	<tr>
		<td colspan="2"><%= f.submit '登録' %></td>
	</tr>
</table>

<% end %>

<%= link_to '戻る', top_login_path %>

app/views/users/show.html.erb
<%= @user.uid %>
<%= @user.exe %>P
<br>
<%= link_to 'ポイント交換', main_point_path %>

<table border="1">
	<tr>
		<th>ID</th>
		<th>uid</th>
		<th>ポイント</th>
		<th>操作</th>
	</tr>

	<tr>
		<td><%= @user.id %></td>
		<td><%= @user.uid %></td>
		<td><%= @user.exe %></td>
		<td>
			<%= link_to 'アカウントの削除', user_path(@user), method: :delete, data: { confirm: '削除していいですか？' } %>
		</td>
	</tr>
</table>

<%= link_to 'プロフィールを変更', users_edit_path %>
<%= link_to 'ホームに戻る', main_index_path %>